### PR TITLE
Update for PureScript 0.7

### PR DESCRIPTION
**Pull request by DavidHarrison**
Similar to Fresheyeball/purescript-context#4. I did also condense the some of the foreign functions, as many of the numbered functions could (unsafely) use similar implementations internally.

### CODE REVIEW

**Comment by DavidHarrison** [comment]
Thanks!

**Comment by Fresheyeball** [comment]
I will cut a realease and do pursuit as soon as I can

**Comment by Fresheyeball** [comment]
@DavidHarrison so, `pulp build && pulp test` passes for me locally, but it doesn't with Travis. Any ideas? Travis was happy before.

**Comment by DavidHarrison** [comment]
I think that's because Travis is pulling PureScript [0.7.3](https://github.com/purescript/purescript/releases/tag/v0.7.3), which has a new check for orphan instances. I think the `Bounded Char` instance has been moved to `purescript-prelude` from `purescript-strings` and so both dependencies would have to be updated. I'll take a look when I get home.

**Comment by Fresheyeball** [comment]
Ok, makes sense. If this package can't build with 0.7.3, maybe we just lock
down the version.

**Comment by DavidHarrison** [comment]
It looks like `purescript-strings` is getting pulled in by `purescript-spec` which locks it at 0.5.3. I'll put in a pull request with `purescript-spec` to fix this. Since it's only a dev-dependency, the library itself should be fine, just that the tests won't run with latest 0.7.3. For now I'll open a pull request to `npm install purescript@0.7.2` and see if that allows Travis to pass.

**Pull request merged**
